---

- name: Congigure Jenkins
  hosts: jenkins
  gather_facts: False
  become: yes
  vars_files:
   - vjenkins.yml

  tasks:
  
  - name: create jenkins respository
    file:
      path: "{{dir}}"
      state: directory

  - name: copy Jenkins   
    copy:
      src: /Users/rafael.oliveira/Downloads/jenkins_2.7.4_all.deb
      dest: "{{dir}}/jenkins_2.7.4_all.deb"
      
  - name: Install a .deb package
    apt:
      deb: "{{dir}}/jenkins_2.7.4_all.deb"
      state: present
      
  - name: Service started
    service:
      name: jenkins
      state: started
      enabled: yes
    

    